name: Node CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        CI: true
